'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srUsuario
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srUsuario.wsUsuarioSoap")>  _
    Public Interface wsUsuarioSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/iniciarSesion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function iniciarSesion(ByVal usu As String, ByVal con As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/iniciarSesion", ReplyAction:="*")>  _
        Function iniciarSesionAsync(ByVal usu As String, ByVal con As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerPreguntaSec", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function obtenerPreguntaSec(ByVal usu As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerPreguntaSec", ReplyAction:="*")>  _
        Function obtenerPreguntaSecAsync(ByVal usu As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/validarRespuestaPregSec", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function validarRespuestaPregSec(ByVal usu As String, ByVal rpta As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/validarRespuestaPregSec", ReplyAction:="*")>  _
        Function validarRespuestaPregSecAsync(ByVal usu As String, ByVal rpta As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerNombreUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function obtenerNombreUsuario(ByVal usu As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerNombreUsuario", ReplyAction:="*")>  _
        Function obtenerNombreUsuarioAsync(ByVal usu As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function generarIDUsuario() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDUsuario", ReplyAction:="*")>  _
        Function generarIDUsuarioAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub guardarUsuario(ByVal id As Integer, ByVal nom As String, ByVal contrasena As String, ByVal nombresCompletos As String, ByVal preguntaSecreta As String, ByVal respuesta As String, ByVal vig As Boolean, ByVal idTipoUsuario As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarUsuario", ReplyAction:="*")>  _
        Function guardarUsuarioAsync(ByVal id As Integer, ByVal nom As String, ByVal contrasena As String, ByVal nombresCompletos As String, ByVal preguntaSecreta As String, ByVal respuesta As String, ByVal vig As Boolean, ByVal idTipoUsuario As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub modificarUsuario(ByVal id As Integer, ByVal nom As String, ByVal contrasena As String, ByVal nombresCompletos As String, ByVal preguntaSecreta As String, ByVal respuesta As String, ByVal vig As Boolean, ByVal idTipoUsuario As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarUsuario", ReplyAction:="*")>  _
        Function modificarUsuarioAsync(ByVal id As Integer, ByVal nom As String, ByVal contrasena As String, ByVal nombresCompletos As String, ByVal preguntaSecreta As String, ByVal respuesta As String, ByVal vig As Boolean, ByVal idTipoUsuario As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub eliminarUsuario(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarUsuario", ReplyAction:="*")>  _
        Function eliminarUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darBajaUsuario(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaUsuario", ReplyAction:="*")>  _
        Function darBajaUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darAltaUsuario(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaUsuario", ReplyAction:="*")>  _
        Function darAltaUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarUsuario(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarUsuario", ReplyAction:="*")>  _
        Function buscarUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarUsuarioPorNombre", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarUsuarioPorNombre(ByVal nombres As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarUsuarioPorNombre", ReplyAction:="*")>  _
        Function buscarUsuarioPorNombreAsync(ByVal nombres As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarUsuarios", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarUsuarios() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarUsuarios", ReplyAction:="*")>  _
        Function listarUsuariosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsUsuarioSoapChannel
        Inherits srUsuario.wsUsuarioSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsUsuarioSoapClient
        Inherits System.ServiceModel.ClientBase(Of srUsuario.wsUsuarioSoap)
        Implements srUsuario.wsUsuarioSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function iniciarSesion(ByVal usu As String, ByVal con As String) As Boolean Implements srUsuario.wsUsuarioSoap.iniciarSesion
            Return MyBase.Channel.iniciarSesion(usu, con)
        End Function
        
        Public Function iniciarSesionAsync(ByVal usu As String, ByVal con As String) As System.Threading.Tasks.Task(Of Boolean) Implements srUsuario.wsUsuarioSoap.iniciarSesionAsync
            Return MyBase.Channel.iniciarSesionAsync(usu, con)
        End Function
        
        Public Function obtenerPreguntaSec(ByVal usu As String) As String Implements srUsuario.wsUsuarioSoap.obtenerPreguntaSec
            Return MyBase.Channel.obtenerPreguntaSec(usu)
        End Function
        
        Public Function obtenerPreguntaSecAsync(ByVal usu As String) As System.Threading.Tasks.Task(Of String) Implements srUsuario.wsUsuarioSoap.obtenerPreguntaSecAsync
            Return MyBase.Channel.obtenerPreguntaSecAsync(usu)
        End Function
        
        Public Function validarRespuestaPregSec(ByVal usu As String, ByVal rpta As String) As Boolean Implements srUsuario.wsUsuarioSoap.validarRespuestaPregSec
            Return MyBase.Channel.validarRespuestaPregSec(usu, rpta)
        End Function
        
        Public Function validarRespuestaPregSecAsync(ByVal usu As String, ByVal rpta As String) As System.Threading.Tasks.Task(Of Boolean) Implements srUsuario.wsUsuarioSoap.validarRespuestaPregSecAsync
            Return MyBase.Channel.validarRespuestaPregSecAsync(usu, rpta)
        End Function
        
        Public Function obtenerNombreUsuario(ByVal usu As String) As String Implements srUsuario.wsUsuarioSoap.obtenerNombreUsuario
            Return MyBase.Channel.obtenerNombreUsuario(usu)
        End Function
        
        Public Function obtenerNombreUsuarioAsync(ByVal usu As String) As System.Threading.Tasks.Task(Of String) Implements srUsuario.wsUsuarioSoap.obtenerNombreUsuarioAsync
            Return MyBase.Channel.obtenerNombreUsuarioAsync(usu)
        End Function
        
        Public Function generarIDUsuario() As Integer Implements srUsuario.wsUsuarioSoap.generarIDUsuario
            Return MyBase.Channel.generarIDUsuario
        End Function
        
        Public Function generarIDUsuarioAsync() As System.Threading.Tasks.Task(Of Integer) Implements srUsuario.wsUsuarioSoap.generarIDUsuarioAsync
            Return MyBase.Channel.generarIDUsuarioAsync
        End Function
        
        Public Sub guardarUsuario(ByVal id As Integer, ByVal nom As String, ByVal contrasena As String, ByVal nombresCompletos As String, ByVal preguntaSecreta As String, ByVal respuesta As String, ByVal vig As Boolean, ByVal idTipoUsuario As Integer) Implements srUsuario.wsUsuarioSoap.guardarUsuario
            MyBase.Channel.guardarUsuario(id, nom, contrasena, nombresCompletos, preguntaSecreta, respuesta, vig, idTipoUsuario)
        End Sub
        
        Public Function guardarUsuarioAsync(ByVal id As Integer, ByVal nom As String, ByVal contrasena As String, ByVal nombresCompletos As String, ByVal preguntaSecreta As String, ByVal respuesta As String, ByVal vig As Boolean, ByVal idTipoUsuario As Integer) As System.Threading.Tasks.Task Implements srUsuario.wsUsuarioSoap.guardarUsuarioAsync
            Return MyBase.Channel.guardarUsuarioAsync(id, nom, contrasena, nombresCompletos, preguntaSecreta, respuesta, vig, idTipoUsuario)
        End Function
        
        Public Sub modificarUsuario(ByVal id As Integer, ByVal nom As String, ByVal contrasena As String, ByVal nombresCompletos As String, ByVal preguntaSecreta As String, ByVal respuesta As String, ByVal vig As Boolean, ByVal idTipoUsuario As Integer) Implements srUsuario.wsUsuarioSoap.modificarUsuario
            MyBase.Channel.modificarUsuario(id, nom, contrasena, nombresCompletos, preguntaSecreta, respuesta, vig, idTipoUsuario)
        End Sub
        
        Public Function modificarUsuarioAsync(ByVal id As Integer, ByVal nom As String, ByVal contrasena As String, ByVal nombresCompletos As String, ByVal preguntaSecreta As String, ByVal respuesta As String, ByVal vig As Boolean, ByVal idTipoUsuario As Integer) As System.Threading.Tasks.Task Implements srUsuario.wsUsuarioSoap.modificarUsuarioAsync
            Return MyBase.Channel.modificarUsuarioAsync(id, nom, contrasena, nombresCompletos, preguntaSecreta, respuesta, vig, idTipoUsuario)
        End Function
        
        Public Sub eliminarUsuario(ByVal id As Integer) Implements srUsuario.wsUsuarioSoap.eliminarUsuario
            MyBase.Channel.eliminarUsuario(id)
        End Sub
        
        Public Function eliminarUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srUsuario.wsUsuarioSoap.eliminarUsuarioAsync
            Return MyBase.Channel.eliminarUsuarioAsync(id)
        End Function
        
        Public Sub darBajaUsuario(ByVal id As Integer) Implements srUsuario.wsUsuarioSoap.darBajaUsuario
            MyBase.Channel.darBajaUsuario(id)
        End Sub
        
        Public Function darBajaUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srUsuario.wsUsuarioSoap.darBajaUsuarioAsync
            Return MyBase.Channel.darBajaUsuarioAsync(id)
        End Function
        
        Public Sub darAltaUsuario(ByVal id As Integer) Implements srUsuario.wsUsuarioSoap.darAltaUsuario
            MyBase.Channel.darAltaUsuario(id)
        End Sub
        
        Public Function darAltaUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srUsuario.wsUsuarioSoap.darAltaUsuarioAsync
            Return MyBase.Channel.darAltaUsuarioAsync(id)
        End Function
        
        Public Function buscarUsuario(ByVal id As Integer) As System.Data.DataTable Implements srUsuario.wsUsuarioSoap.buscarUsuario
            Return MyBase.Channel.buscarUsuario(id)
        End Function
        
        Public Function buscarUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srUsuario.wsUsuarioSoap.buscarUsuarioAsync
            Return MyBase.Channel.buscarUsuarioAsync(id)
        End Function
        
        Public Function buscarUsuarioPorNombre(ByVal nombres As String) As System.Data.DataTable Implements srUsuario.wsUsuarioSoap.buscarUsuarioPorNombre
            Return MyBase.Channel.buscarUsuarioPorNombre(nombres)
        End Function
        
        Public Function buscarUsuarioPorNombreAsync(ByVal nombres As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srUsuario.wsUsuarioSoap.buscarUsuarioPorNombreAsync
            Return MyBase.Channel.buscarUsuarioPorNombreAsync(nombres)
        End Function
        
        Public Function listarUsuarios() As System.Data.DataTable Implements srUsuario.wsUsuarioSoap.listarUsuarios
            Return MyBase.Channel.listarUsuarios
        End Function
        
        Public Function listarUsuariosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srUsuario.wsUsuarioSoap.listarUsuariosAsync
            Return MyBase.Channel.listarUsuariosAsync
        End Function
    End Class
End Namespace
