'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srCliente
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srCliente.wsClienteSoap")>  _
    Public Interface wsClienteSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function generarIDCliente() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDCliente", ReplyAction:="*")>  _
        Function generarIDClienteAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub guardarCliente(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarCliente", ReplyAction:="*")>  _
        Function guardarClienteAsync(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub modificarCliente(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarCliente", ReplyAction:="*")>  _
        Function modificarClienteAsync(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub eliminarCliente(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarCliente", ReplyAction:="*")>  _
        Function eliminarClienteAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darBajaCliente(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaCliente", ReplyAction:="*")>  _
        Function darBajaClienteAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darAltaCliente(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaCliente", ReplyAction:="*")>  _
        Function darAltaClienteAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarCliente(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCliente", ReplyAction:="*")>  _
        Function buscarClienteAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarClientePorDNI", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarClientePorDNI(ByVal dni As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarClientePorDNI", ReplyAction:="*")>  _
        Function buscarClientePorDNIAsync(ByVal dni As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarClientes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarClientes() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarClientes", ReplyAction:="*")>  _
        Function listarClientesAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarClientesVigentes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarClientesVigentes() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarClientesVigentes", ReplyAction:="*")>  _
        Function listarClientesVigentesAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificarCliente", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerificarCliente(ByVal idCliente As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificarCliente", ReplyAction:="*")>  _
        Function VerificarClienteAsync(ByVal idCliente As Integer) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsClienteSoapChannel
        Inherits srCliente.wsClienteSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsClienteSoapClient
        Inherits System.ServiceModel.ClientBase(Of srCliente.wsClienteSoap)
        Implements srCliente.wsClienteSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function generarIDCliente() As Integer Implements srCliente.wsClienteSoap.generarIDCliente
            Return MyBase.Channel.generarIDCliente
        End Function
        
        Public Function generarIDClienteAsync() As System.Threading.Tasks.Task(Of Integer) Implements srCliente.wsClienteSoap.generarIDClienteAsync
            Return MyBase.Channel.generarIDClienteAsync
        End Function
        
        Public Sub guardarCliente(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) Implements srCliente.wsClienteSoap.guardarCliente
            MyBase.Channel.guardarCliente(id, dni, nom, ape, tel, cor, est)
        End Sub
        
        Public Function guardarClienteAsync(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) As System.Threading.Tasks.Task Implements srCliente.wsClienteSoap.guardarClienteAsync
            Return MyBase.Channel.guardarClienteAsync(id, dni, nom, ape, tel, cor, est)
        End Function
        
        Public Sub modificarCliente(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) Implements srCliente.wsClienteSoap.modificarCliente
            MyBase.Channel.modificarCliente(id, dni, nom, ape, tel, cor, est)
        End Sub
        
        Public Function modificarClienteAsync(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) As System.Threading.Tasks.Task Implements srCliente.wsClienteSoap.modificarClienteAsync
            Return MyBase.Channel.modificarClienteAsync(id, dni, nom, ape, tel, cor, est)
        End Function
        
        Public Sub eliminarCliente(ByVal id As Integer) Implements srCliente.wsClienteSoap.eliminarCliente
            MyBase.Channel.eliminarCliente(id)
        End Sub
        
        Public Function eliminarClienteAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCliente.wsClienteSoap.eliminarClienteAsync
            Return MyBase.Channel.eliminarClienteAsync(id)
        End Function
        
        Public Sub darBajaCliente(ByVal id As Integer) Implements srCliente.wsClienteSoap.darBajaCliente
            MyBase.Channel.darBajaCliente(id)
        End Sub
        
        Public Function darBajaClienteAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCliente.wsClienteSoap.darBajaClienteAsync
            Return MyBase.Channel.darBajaClienteAsync(id)
        End Function
        
        Public Sub darAltaCliente(ByVal id As Integer) Implements srCliente.wsClienteSoap.darAltaCliente
            MyBase.Channel.darAltaCliente(id)
        End Sub
        
        Public Function darAltaClienteAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCliente.wsClienteSoap.darAltaClienteAsync
            Return MyBase.Channel.darAltaClienteAsync(id)
        End Function
        
        Public Function buscarCliente(ByVal id As Integer) As System.Data.DataTable Implements srCliente.wsClienteSoap.buscarCliente
            Return MyBase.Channel.buscarCliente(id)
        End Function
        
        Public Function buscarClienteAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCliente.wsClienteSoap.buscarClienteAsync
            Return MyBase.Channel.buscarClienteAsync(id)
        End Function
        
        Public Function buscarClientePorDNI(ByVal dni As String) As System.Data.DataTable Implements srCliente.wsClienteSoap.buscarClientePorDNI
            Return MyBase.Channel.buscarClientePorDNI(dni)
        End Function
        
        Public Function buscarClientePorDNIAsync(ByVal dni As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCliente.wsClienteSoap.buscarClientePorDNIAsync
            Return MyBase.Channel.buscarClientePorDNIAsync(dni)
        End Function
        
        Public Function listarClientes() As System.Data.DataTable Implements srCliente.wsClienteSoap.listarClientes
            Return MyBase.Channel.listarClientes
        End Function
        
        Public Function listarClientesAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCliente.wsClienteSoap.listarClientesAsync
            Return MyBase.Channel.listarClientesAsync
        End Function
        
        Public Function listarClientesVigentes() As System.Data.DataTable Implements srCliente.wsClienteSoap.listarClientesVigentes
            Return MyBase.Channel.listarClientesVigentes
        End Function
        
        Public Function listarClientesVigentesAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCliente.wsClienteSoap.listarClientesVigentesAsync
            Return MyBase.Channel.listarClientesVigentesAsync
        End Function
        
        Public Function VerificarCliente(ByVal idCliente As Integer) As Boolean Implements srCliente.wsClienteSoap.VerificarCliente
            Return MyBase.Channel.VerificarCliente(idCliente)
        End Function
        
        Public Function VerificarClienteAsync(ByVal idCliente As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements srCliente.wsClienteSoap.VerificarClienteAsync
            Return MyBase.Channel.VerificarClienteAsync(idCliente)
        End Function
    End Class
End Namespace
