'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srProducto
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srProducto.wsProductoSoap")>  _
    Public Interface wsProductoSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function generarIDProducto() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDProducto", ReplyAction:="*")>  _
        Function generarIDProductoAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub guardarProducto(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal precio As Decimal, ByVal vig As Boolean, ByVal idTipo As Integer, ByVal idCarta As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarProducto", ReplyAction:="*")>  _
        Function guardarProductoAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal precio As Decimal, ByVal vig As Boolean, ByVal idTipo As Integer, ByVal idCarta As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub modificarProducto(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal precio As Decimal, ByVal vig As Boolean, ByVal idTipo As Integer, ByVal idCarta As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarProducto", ReplyAction:="*")>  _
        Function modificarProductoAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal precio As Decimal, ByVal vig As Boolean, ByVal idTipo As Integer, ByVal idCarta As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub eliminarProducto(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarProducto", ReplyAction:="*")>  _
        Function eliminarProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darBajaProducto(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaProducto", ReplyAction:="*")>  _
        Function darBajaProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darAltaProducto(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaProducto", ReplyAction:="*")>  _
        Function darAltaProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarProducto(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarProducto", ReplyAction:="*")>  _
        Function buscarProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarProductos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarProductos() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarProductos", ReplyAction:="*")>  _
        Function listarProductosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarProductosPorIdCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarProductosPorIdCarta(ByVal idCarta As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarProductosPorIdCarta", ReplyAction:="*")>  _
        Function ListarProductosPorIdCartaAsync(ByVal idCarta As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsProductoSoapChannel
        Inherits srProducto.wsProductoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsProductoSoapClient
        Inherits System.ServiceModel.ClientBase(Of srProducto.wsProductoSoap)
        Implements srProducto.wsProductoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function generarIDProducto() As Integer Implements srProducto.wsProductoSoap.generarIDProducto
            Return MyBase.Channel.generarIDProducto
        End Function
        
        Public Function generarIDProductoAsync() As System.Threading.Tasks.Task(Of Integer) Implements srProducto.wsProductoSoap.generarIDProductoAsync
            Return MyBase.Channel.generarIDProductoAsync
        End Function
        
        Public Sub guardarProducto(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal precio As Decimal, ByVal vig As Boolean, ByVal idTipo As Integer, ByVal idCarta As Integer) Implements srProducto.wsProductoSoap.guardarProducto
            MyBase.Channel.guardarProducto(id, nom, desc, precio, vig, idTipo, idCarta)
        End Sub
        
        Public Function guardarProductoAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal precio As Decimal, ByVal vig As Boolean, ByVal idTipo As Integer, ByVal idCarta As Integer) As System.Threading.Tasks.Task Implements srProducto.wsProductoSoap.guardarProductoAsync
            Return MyBase.Channel.guardarProductoAsync(id, nom, desc, precio, vig, idTipo, idCarta)
        End Function
        
        Public Sub modificarProducto(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal precio As Decimal, ByVal vig As Boolean, ByVal idTipo As Integer, ByVal idCarta As Integer) Implements srProducto.wsProductoSoap.modificarProducto
            MyBase.Channel.modificarProducto(id, nom, desc, precio, vig, idTipo, idCarta)
        End Sub
        
        Public Function modificarProductoAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal precio As Decimal, ByVal vig As Boolean, ByVal idTipo As Integer, ByVal idCarta As Integer) As System.Threading.Tasks.Task Implements srProducto.wsProductoSoap.modificarProductoAsync
            Return MyBase.Channel.modificarProductoAsync(id, nom, desc, precio, vig, idTipo, idCarta)
        End Function
        
        Public Sub eliminarProducto(ByVal id As Integer) Implements srProducto.wsProductoSoap.eliminarProducto
            MyBase.Channel.eliminarProducto(id)
        End Sub
        
        Public Function eliminarProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srProducto.wsProductoSoap.eliminarProductoAsync
            Return MyBase.Channel.eliminarProductoAsync(id)
        End Function
        
        Public Sub darBajaProducto(ByVal id As Integer) Implements srProducto.wsProductoSoap.darBajaProducto
            MyBase.Channel.darBajaProducto(id)
        End Sub
        
        Public Function darBajaProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srProducto.wsProductoSoap.darBajaProductoAsync
            Return MyBase.Channel.darBajaProductoAsync(id)
        End Function
        
        Public Sub darAltaProducto(ByVal id As Integer) Implements srProducto.wsProductoSoap.darAltaProducto
            MyBase.Channel.darAltaProducto(id)
        End Sub
        
        Public Function darAltaProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srProducto.wsProductoSoap.darAltaProductoAsync
            Return MyBase.Channel.darAltaProductoAsync(id)
        End Function
        
        Public Function buscarProducto(ByVal id As Integer) As System.Data.DataTable Implements srProducto.wsProductoSoap.buscarProducto
            Return MyBase.Channel.buscarProducto(id)
        End Function
        
        Public Function buscarProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srProducto.wsProductoSoap.buscarProductoAsync
            Return MyBase.Channel.buscarProductoAsync(id)
        End Function
        
        Public Function listarProductos() As System.Data.DataTable Implements srProducto.wsProductoSoap.listarProductos
            Return MyBase.Channel.listarProductos
        End Function
        
        Public Function listarProductosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srProducto.wsProductoSoap.listarProductosAsync
            Return MyBase.Channel.listarProductosAsync
        End Function
        
        Public Function ListarProductosPorIdCarta(ByVal idCarta As Integer) As System.Data.DataTable Implements srProducto.wsProductoSoap.ListarProductosPorIdCarta
            Return MyBase.Channel.ListarProductosPorIdCarta(idCarta)
        End Function
        
        Public Function ListarProductosPorIdCartaAsync(ByVal idCarta As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srProducto.wsProductoSoap.ListarProductosPorIdCartaAsync
            Return MyBase.Channel.ListarProductosPorIdCartaAsync(idCarta)
        End Function
    End Class
End Namespace
