'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srCarta
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srCarta.wsCartaSoap")>  _
    Public Interface wsCartaSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function generarIDCarta() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDCarta", ReplyAction:="*")>  _
        Function generarIDCartaAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub guardarCarta(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarCarta", ReplyAction:="*")>  _
        Function guardarCartaAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub modificarCarta(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarCarta", ReplyAction:="*")>  _
        Function modificarCartaAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub eliminarCarta(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarCarta", ReplyAction:="*")>  _
        Function eliminarCartaAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darBajaCarta(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaCarta", ReplyAction:="*")>  _
        Function darBajaCartaAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darAltaCarta(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaCarta", ReplyAction:="*")>  _
        Function darAltaCartaAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarCarta(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCarta", ReplyAction:="*")>  _
        Function buscarCartaAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCartaPorNombre", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarCartaPorNombre(ByVal nombre As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCartaPorNombre", ReplyAction:="*")>  _
        Function buscarCartaPorNombreAsync(ByVal nombre As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarCartas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarCartas() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarCartas", ReplyAction:="*")>  _
        Function listarCartasAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificarCarta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerificarCarta(ByVal idCarta As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificarCarta", ReplyAction:="*")>  _
        Function VerificarCartaAsync(ByVal idCarta As Integer) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsCartaSoapChannel
        Inherits srCarta.wsCartaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsCartaSoapClient
        Inherits System.ServiceModel.ClientBase(Of srCarta.wsCartaSoap)
        Implements srCarta.wsCartaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function generarIDCarta() As Integer Implements srCarta.wsCartaSoap.generarIDCarta
            Return MyBase.Channel.generarIDCarta
        End Function
        
        Public Function generarIDCartaAsync() As System.Threading.Tasks.Task(Of Integer) Implements srCarta.wsCartaSoap.generarIDCartaAsync
            Return MyBase.Channel.generarIDCartaAsync
        End Function
        
        Public Sub guardarCarta(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) Implements srCarta.wsCartaSoap.guardarCarta
            MyBase.Channel.guardarCarta(id, nom, desc, vig)
        End Sub
        
        Public Function guardarCartaAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task Implements srCarta.wsCartaSoap.guardarCartaAsync
            Return MyBase.Channel.guardarCartaAsync(id, nom, desc, vig)
        End Function
        
        Public Sub modificarCarta(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) Implements srCarta.wsCartaSoap.modificarCarta
            MyBase.Channel.modificarCarta(id, nom, desc, vig)
        End Sub
        
        Public Function modificarCartaAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task Implements srCarta.wsCartaSoap.modificarCartaAsync
            Return MyBase.Channel.modificarCartaAsync(id, nom, desc, vig)
        End Function
        
        Public Sub eliminarCarta(ByVal id As Integer) Implements srCarta.wsCartaSoap.eliminarCarta
            MyBase.Channel.eliminarCarta(id)
        End Sub
        
        Public Function eliminarCartaAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCarta.wsCartaSoap.eliminarCartaAsync
            Return MyBase.Channel.eliminarCartaAsync(id)
        End Function
        
        Public Sub darBajaCarta(ByVal id As Integer) Implements srCarta.wsCartaSoap.darBajaCarta
            MyBase.Channel.darBajaCarta(id)
        End Sub
        
        Public Function darBajaCartaAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCarta.wsCartaSoap.darBajaCartaAsync
            Return MyBase.Channel.darBajaCartaAsync(id)
        End Function
        
        Public Sub darAltaCarta(ByVal id As Integer) Implements srCarta.wsCartaSoap.darAltaCarta
            MyBase.Channel.darAltaCarta(id)
        End Sub
        
        Public Function darAltaCartaAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCarta.wsCartaSoap.darAltaCartaAsync
            Return MyBase.Channel.darAltaCartaAsync(id)
        End Function
        
        Public Function buscarCarta(ByVal id As Integer) As System.Data.DataTable Implements srCarta.wsCartaSoap.buscarCarta
            Return MyBase.Channel.buscarCarta(id)
        End Function
        
        Public Function buscarCartaAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCarta.wsCartaSoap.buscarCartaAsync
            Return MyBase.Channel.buscarCartaAsync(id)
        End Function
        
        Public Function buscarCartaPorNombre(ByVal nombre As String) As System.Data.DataTable Implements srCarta.wsCartaSoap.buscarCartaPorNombre
            Return MyBase.Channel.buscarCartaPorNombre(nombre)
        End Function
        
        Public Function buscarCartaPorNombreAsync(ByVal nombre As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCarta.wsCartaSoap.buscarCartaPorNombreAsync
            Return MyBase.Channel.buscarCartaPorNombreAsync(nombre)
        End Function
        
        Public Function listarCartas() As System.Data.DataTable Implements srCarta.wsCartaSoap.listarCartas
            Return MyBase.Channel.listarCartas
        End Function
        
        Public Function listarCartasAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCarta.wsCartaSoap.listarCartasAsync
            Return MyBase.Channel.listarCartasAsync
        End Function
        
        Public Function VerificarCarta(ByVal idCarta As Integer) As Boolean Implements srCarta.wsCartaSoap.VerificarCarta
            Return MyBase.Channel.VerificarCarta(idCarta)
        End Function
        
        Public Function VerificarCartaAsync(ByVal idCarta As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements srCarta.wsCartaSoap.VerificarCartaAsync
            Return MyBase.Channel.VerificarCartaAsync(idCarta)
        End Function
    End Class
End Namespace
