'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srCajero
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srCajero.wsCajeroSoap")>  _
    Public Interface wsCajeroSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDCajero", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function generarIDCajero() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDCajero", ReplyAction:="*")>  _
        Function generarIDCajeroAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarCajero", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub guardarCajero(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarCajero", ReplyAction:="*")>  _
        Function guardarCajeroAsync(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarCajero", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub modificarCajero(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarCajero", ReplyAction:="*")>  _
        Function modificarCajeroAsync(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarCajero", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub eliminarCajero(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarCajero", ReplyAction:="*")>  _
        Function eliminarCajeroAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaCajero", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darBajaCajero(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaCajero", ReplyAction:="*")>  _
        Function darBajaCajeroAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaCajero", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darAltaCajero(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaCajero", ReplyAction:="*")>  _
        Function darAltaCajeroAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCajero", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarCajero(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCajero", ReplyAction:="*")>  _
        Function buscarCajeroAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCajeroPorDNI", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarCajeroPorDNI(ByVal dni As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarCajeroPorDNI", ReplyAction:="*")>  _
        Function buscarCajeroPorDNIAsync(ByVal dni As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarCajeros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarCajeros() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarCajeros", ReplyAction:="*")>  _
        Function listarCajerosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarCajerosCompleto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarCajerosCompleto() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarCajerosCompleto", ReplyAction:="*")>  _
        Function listarCajerosCompletoAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarCajerosVigentes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarCajerosVigentes() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarCajerosVigentes", ReplyAction:="*")>  _
        Function listarCajerosVigentesAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificarCajero", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerificarCajero(ByVal idCajero As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificarCajero", ReplyAction:="*")>  _
        Function VerificarCajeroAsync(ByVal idCajero As Integer) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsCajeroSoapChannel
        Inherits srCajero.wsCajeroSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsCajeroSoapClient
        Inherits System.ServiceModel.ClientBase(Of srCajero.wsCajeroSoap)
        Implements srCajero.wsCajeroSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function generarIDCajero() As Integer Implements srCajero.wsCajeroSoap.generarIDCajero
            Return MyBase.Channel.generarIDCajero
        End Function
        
        Public Function generarIDCajeroAsync() As System.Threading.Tasks.Task(Of Integer) Implements srCajero.wsCajeroSoap.generarIDCajeroAsync
            Return MyBase.Channel.generarIDCajeroAsync
        End Function
        
        Public Sub guardarCajero(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) Implements srCajero.wsCajeroSoap.guardarCajero
            MyBase.Channel.guardarCajero(id, dni, nom, ape, tel, cor, est)
        End Sub
        
        Public Function guardarCajeroAsync(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) As System.Threading.Tasks.Task Implements srCajero.wsCajeroSoap.guardarCajeroAsync
            Return MyBase.Channel.guardarCajeroAsync(id, dni, nom, ape, tel, cor, est)
        End Function
        
        Public Sub modificarCajero(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) Implements srCajero.wsCajeroSoap.modificarCajero
            MyBase.Channel.modificarCajero(id, dni, nom, ape, tel, cor, est)
        End Sub
        
        Public Function modificarCajeroAsync(ByVal id As Integer, ByVal dni As String, ByVal nom As String, ByVal ape As String, ByVal tel As String, ByVal cor As String, ByVal est As Boolean) As System.Threading.Tasks.Task Implements srCajero.wsCajeroSoap.modificarCajeroAsync
            Return MyBase.Channel.modificarCajeroAsync(id, dni, nom, ape, tel, cor, est)
        End Function
        
        Public Sub eliminarCajero(ByVal id As Integer) Implements srCajero.wsCajeroSoap.eliminarCajero
            MyBase.Channel.eliminarCajero(id)
        End Sub
        
        Public Function eliminarCajeroAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCajero.wsCajeroSoap.eliminarCajeroAsync
            Return MyBase.Channel.eliminarCajeroAsync(id)
        End Function
        
        Public Sub darBajaCajero(ByVal id As Integer) Implements srCajero.wsCajeroSoap.darBajaCajero
            MyBase.Channel.darBajaCajero(id)
        End Sub
        
        Public Function darBajaCajeroAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCajero.wsCajeroSoap.darBajaCajeroAsync
            Return MyBase.Channel.darBajaCajeroAsync(id)
        End Function
        
        Public Sub darAltaCajero(ByVal id As Integer) Implements srCajero.wsCajeroSoap.darAltaCajero
            MyBase.Channel.darAltaCajero(id)
        End Sub
        
        Public Function darAltaCajeroAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srCajero.wsCajeroSoap.darAltaCajeroAsync
            Return MyBase.Channel.darAltaCajeroAsync(id)
        End Function
        
        Public Function buscarCajero(ByVal id As Integer) As System.Data.DataTable Implements srCajero.wsCajeroSoap.buscarCajero
            Return MyBase.Channel.buscarCajero(id)
        End Function
        
        Public Function buscarCajeroAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCajero.wsCajeroSoap.buscarCajeroAsync
            Return MyBase.Channel.buscarCajeroAsync(id)
        End Function
        
        Public Function buscarCajeroPorDNI(ByVal dni As String) As System.Data.DataTable Implements srCajero.wsCajeroSoap.buscarCajeroPorDNI
            Return MyBase.Channel.buscarCajeroPorDNI(dni)
        End Function
        
        Public Function buscarCajeroPorDNIAsync(ByVal dni As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCajero.wsCajeroSoap.buscarCajeroPorDNIAsync
            Return MyBase.Channel.buscarCajeroPorDNIAsync(dni)
        End Function
        
        Public Function listarCajeros() As System.Data.DataTable Implements srCajero.wsCajeroSoap.listarCajeros
            Return MyBase.Channel.listarCajeros
        End Function
        
        Public Function listarCajerosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCajero.wsCajeroSoap.listarCajerosAsync
            Return MyBase.Channel.listarCajerosAsync
        End Function
        
        Public Function listarCajerosCompleto() As System.Data.DataTable Implements srCajero.wsCajeroSoap.listarCajerosCompleto
            Return MyBase.Channel.listarCajerosCompleto
        End Function
        
        Public Function listarCajerosCompletoAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCajero.wsCajeroSoap.listarCajerosCompletoAsync
            Return MyBase.Channel.listarCajerosCompletoAsync
        End Function
        
        Public Function listarCajerosVigentes() As System.Data.DataTable Implements srCajero.wsCajeroSoap.listarCajerosVigentes
            Return MyBase.Channel.listarCajerosVigentes
        End Function
        
        Public Function listarCajerosVigentesAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCajero.wsCajeroSoap.listarCajerosVigentesAsync
            Return MyBase.Channel.listarCajerosVigentesAsync
        End Function
        
        Public Function VerificarCajero(ByVal idCajero As Integer) As Boolean Implements srCajero.wsCajeroSoap.VerificarCajero
            Return MyBase.Channel.VerificarCajero(idCajero)
        End Function
        
        Public Function VerificarCajeroAsync(ByVal idCajero As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements srCajero.wsCajeroSoap.VerificarCajeroAsync
            Return MyBase.Channel.VerificarCajeroAsync(idCajero)
        End Function
    End Class
End Namespace
