'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srTipoUsuario
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srTipoUsuario.wsTipoUsuarioSoap")>  _
    Public Interface wsTipoUsuarioSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDTipoUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function generarIDTipoUsuario() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDTipoUsuario", ReplyAction:="*")>  _
        Function generarIDTipoUsuarioAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarTipoUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub guardarTipoUsuario(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarTipoUsuario", ReplyAction:="*")>  _
        Function guardarTipoUsuarioAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarTipoUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub modificarTipoUsuario(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarTipoUsuario", ReplyAction:="*")>  _
        Function modificarTipoUsuarioAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarTipoUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub eliminarTipoUsuario(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarTipoUsuario", ReplyAction:="*")>  _
        Function eliminarTipoUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaTipoUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darBajaTipoUsuario(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaTipoUsuario", ReplyAction:="*")>  _
        Function darBajaTipoUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaTipoUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darAltaTipoUsuario(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaTipoUsuario", ReplyAction:="*")>  _
        Function darAltaTipoUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarTipoUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarTipoUsuario(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarTipoUsuario", ReplyAction:="*")>  _
        Function buscarTipoUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarTiposUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarTiposUsuario() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarTiposUsuario", ReplyAction:="*")>  _
        Function listarTiposUsuarioAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsTipoUsuarioSoapChannel
        Inherits srTipoUsuario.wsTipoUsuarioSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsTipoUsuarioSoapClient
        Inherits System.ServiceModel.ClientBase(Of srTipoUsuario.wsTipoUsuarioSoap)
        Implements srTipoUsuario.wsTipoUsuarioSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function generarIDTipoUsuario() As Integer Implements srTipoUsuario.wsTipoUsuarioSoap.generarIDTipoUsuario
            Return MyBase.Channel.generarIDTipoUsuario
        End Function
        
        Public Function generarIDTipoUsuarioAsync() As System.Threading.Tasks.Task(Of Integer) Implements srTipoUsuario.wsTipoUsuarioSoap.generarIDTipoUsuarioAsync
            Return MyBase.Channel.generarIDTipoUsuarioAsync
        End Function
        
        Public Sub guardarTipoUsuario(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) Implements srTipoUsuario.wsTipoUsuarioSoap.guardarTipoUsuario
            MyBase.Channel.guardarTipoUsuario(id, nom, desc, vig)
        End Sub
        
        Public Function guardarTipoUsuarioAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task Implements srTipoUsuario.wsTipoUsuarioSoap.guardarTipoUsuarioAsync
            Return MyBase.Channel.guardarTipoUsuarioAsync(id, nom, desc, vig)
        End Function
        
        Public Sub modificarTipoUsuario(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) Implements srTipoUsuario.wsTipoUsuarioSoap.modificarTipoUsuario
            MyBase.Channel.modificarTipoUsuario(id, nom, desc, vig)
        End Sub
        
        Public Function modificarTipoUsuarioAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task Implements srTipoUsuario.wsTipoUsuarioSoap.modificarTipoUsuarioAsync
            Return MyBase.Channel.modificarTipoUsuarioAsync(id, nom, desc, vig)
        End Function
        
        Public Sub eliminarTipoUsuario(ByVal id As Integer) Implements srTipoUsuario.wsTipoUsuarioSoap.eliminarTipoUsuario
            MyBase.Channel.eliminarTipoUsuario(id)
        End Sub
        
        Public Function eliminarTipoUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srTipoUsuario.wsTipoUsuarioSoap.eliminarTipoUsuarioAsync
            Return MyBase.Channel.eliminarTipoUsuarioAsync(id)
        End Function
        
        Public Sub darBajaTipoUsuario(ByVal id As Integer) Implements srTipoUsuario.wsTipoUsuarioSoap.darBajaTipoUsuario
            MyBase.Channel.darBajaTipoUsuario(id)
        End Sub
        
        Public Function darBajaTipoUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srTipoUsuario.wsTipoUsuarioSoap.darBajaTipoUsuarioAsync
            Return MyBase.Channel.darBajaTipoUsuarioAsync(id)
        End Function
        
        Public Sub darAltaTipoUsuario(ByVal id As Integer) Implements srTipoUsuario.wsTipoUsuarioSoap.darAltaTipoUsuario
            MyBase.Channel.darAltaTipoUsuario(id)
        End Sub
        
        Public Function darAltaTipoUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srTipoUsuario.wsTipoUsuarioSoap.darAltaTipoUsuarioAsync
            Return MyBase.Channel.darAltaTipoUsuarioAsync(id)
        End Function
        
        Public Function buscarTipoUsuario(ByVal id As Integer) As System.Data.DataTable Implements srTipoUsuario.wsTipoUsuarioSoap.buscarTipoUsuario
            Return MyBase.Channel.buscarTipoUsuario(id)
        End Function
        
        Public Function buscarTipoUsuarioAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srTipoUsuario.wsTipoUsuarioSoap.buscarTipoUsuarioAsync
            Return MyBase.Channel.buscarTipoUsuarioAsync(id)
        End Function
        
        Public Function listarTiposUsuario() As System.Data.DataTable Implements srTipoUsuario.wsTipoUsuarioSoap.listarTiposUsuario
            Return MyBase.Channel.listarTiposUsuario
        End Function
        
        Public Function listarTiposUsuarioAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srTipoUsuario.wsTipoUsuarioSoap.listarTiposUsuarioAsync
            Return MyBase.Channel.listarTiposUsuarioAsync
        End Function
    End Class
End Namespace
