'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srCierreCajaLogica
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srCierreCajaLogica.wsCierreCajaLogicaSoap")>  _
    Public Interface wsCierreCajaLogicaSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarCajeros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarCajeros() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarCajeros", ReplyAction:="*")>  _
        Function ListarCajerosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CerrarCaja", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CerrarCaja(ByVal idCajero As Integer, ByVal nombreUsuario As String, ByVal fecha As Date, ByVal total As Decimal, ByVal moneda As String, ByVal detalles() As srCierreCajaLogica.DetalleArqueoItem) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CerrarCaja", ReplyAction:="*")>  _
        Function CerrarCajaAsync(ByVal idCajero As Integer, ByVal nombreUsuario As String, ByVal fecha As Date, ByVal total As Decimal, ByVal moneda As String, ByVal detalles() As srCierreCajaLogica.DetalleArqueoItem) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarCierres", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarCierres() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarCierres", ReplyAction:="*")>  _
        Function ListarCierresAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetalleArqueoItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descripcionField As String
        
        Private montoField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property monto() As Decimal
            Get
                Return Me.montoField
            End Get
            Set
                Me.montoField = value
                Me.RaisePropertyChanged("monto")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsCierreCajaLogicaSoapChannel
        Inherits srCierreCajaLogica.wsCierreCajaLogicaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsCierreCajaLogicaSoapClient
        Inherits System.ServiceModel.ClientBase(Of srCierreCajaLogica.wsCierreCajaLogicaSoap)
        Implements srCierreCajaLogica.wsCierreCajaLogicaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListarCajeros() As System.Data.DataTable Implements srCierreCajaLogica.wsCierreCajaLogicaSoap.ListarCajeros
            Return MyBase.Channel.ListarCajeros
        End Function
        
        Public Function ListarCajerosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCierreCajaLogica.wsCierreCajaLogicaSoap.ListarCajerosAsync
            Return MyBase.Channel.ListarCajerosAsync
        End Function
        
        Public Function CerrarCaja(ByVal idCajero As Integer, ByVal nombreUsuario As String, ByVal fecha As Date, ByVal total As Decimal, ByVal moneda As String, ByVal detalles() As srCierreCajaLogica.DetalleArqueoItem) As Integer Implements srCierreCajaLogica.wsCierreCajaLogicaSoap.CerrarCaja
            Return MyBase.Channel.CerrarCaja(idCajero, nombreUsuario, fecha, total, moneda, detalles)
        End Function
        
        Public Function CerrarCajaAsync(ByVal idCajero As Integer, ByVal nombreUsuario As String, ByVal fecha As Date, ByVal total As Decimal, ByVal moneda As String, ByVal detalles() As srCierreCajaLogica.DetalleArqueoItem) As System.Threading.Tasks.Task(Of Integer) Implements srCierreCajaLogica.wsCierreCajaLogicaSoap.CerrarCajaAsync
            Return MyBase.Channel.CerrarCajaAsync(idCajero, nombreUsuario, fecha, total, moneda, detalles)
        End Function
        
        Public Function ListarCierres() As System.Data.DataTable Implements srCierreCajaLogica.wsCierreCajaLogicaSoap.ListarCierres
            Return MyBase.Channel.ListarCierres
        End Function
        
        Public Function ListarCierresAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srCierreCajaLogica.wsCierreCajaLogicaSoap.ListarCierresAsync
            Return MyBase.Channel.ListarCierresAsync
        End Function
    End Class
End Namespace
