'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srAperturaCajaLogica
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srAperturaCajaLogica.wsAperturaCajaLogicaSoap")>  _
    Public Interface wsAperturaCajaLogicaSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarCajeros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarCajeros() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarCajeros", ReplyAction:="*")>  _
        Function ListarCajerosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AbrirCaja", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AbrirCaja(ByVal idCajero As Integer, ByVal nombreUsuario As String, ByVal fecha As Date, ByVal base As Decimal, ByVal moneda As String, ByVal estado As String, ByVal detalles() As srAperturaCajaLogica.DetalleArqueoItem) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AbrirCaja", ReplyAction:="*")>  _
        Function AbrirCajaAsync(ByVal idCajero As Integer, ByVal nombreUsuario As String, ByVal fecha As Date, ByVal base As Decimal, ByVal moneda As String, ByVal estado As String, ByVal detalles() As srAperturaCajaLogica.DetalleArqueoItem) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarAperturas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarAperturas() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarAperturas", ReplyAction:="*")>  _
        Function ListarAperturasAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetalleArqueoItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descripcionField As String
        
        Private montoField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property monto() As Decimal
            Get
                Return Me.montoField
            End Get
            Set
                Me.montoField = value
                Me.RaisePropertyChanged("monto")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsAperturaCajaLogicaSoapChannel
        Inherits srAperturaCajaLogica.wsAperturaCajaLogicaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsAperturaCajaLogicaSoapClient
        Inherits System.ServiceModel.ClientBase(Of srAperturaCajaLogica.wsAperturaCajaLogicaSoap)
        Implements srAperturaCajaLogica.wsAperturaCajaLogicaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListarCajeros() As System.Data.DataTable Implements srAperturaCajaLogica.wsAperturaCajaLogicaSoap.ListarCajeros
            Return MyBase.Channel.ListarCajeros
        End Function
        
        Public Function ListarCajerosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srAperturaCajaLogica.wsAperturaCajaLogicaSoap.ListarCajerosAsync
            Return MyBase.Channel.ListarCajerosAsync
        End Function
        
        Public Function AbrirCaja(ByVal idCajero As Integer, ByVal nombreUsuario As String, ByVal fecha As Date, ByVal base As Decimal, ByVal moneda As String, ByVal estado As String, ByVal detalles() As srAperturaCajaLogica.DetalleArqueoItem) As Integer Implements srAperturaCajaLogica.wsAperturaCajaLogicaSoap.AbrirCaja
            Return MyBase.Channel.AbrirCaja(idCajero, nombreUsuario, fecha, base, moneda, estado, detalles)
        End Function
        
        Public Function AbrirCajaAsync(ByVal idCajero As Integer, ByVal nombreUsuario As String, ByVal fecha As Date, ByVal base As Decimal, ByVal moneda As String, ByVal estado As String, ByVal detalles() As srAperturaCajaLogica.DetalleArqueoItem) As System.Threading.Tasks.Task(Of Integer) Implements srAperturaCajaLogica.wsAperturaCajaLogicaSoap.AbrirCajaAsync
            Return MyBase.Channel.AbrirCajaAsync(idCajero, nombreUsuario, fecha, base, moneda, estado, detalles)
        End Function
        
        Public Function ListarAperturas() As System.Data.DataTable Implements srAperturaCajaLogica.wsAperturaCajaLogicaSoap.ListarAperturas
            Return MyBase.Channel.ListarAperturas
        End Function
        
        Public Function ListarAperturasAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srAperturaCajaLogica.wsAperturaCajaLogicaSoap.ListarAperturasAsync
            Return MyBase.Channel.ListarAperturasAsync
        End Function
    End Class
End Namespace
