'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srMesa
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srMesa.wsMesaSoap")>  _
    Public Interface wsMesaSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function generarIDMesa() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDMesa", ReplyAction:="*")>  _
        Function generarIDMesaAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub guardarMesa(ByVal id As Integer, ByVal numero As Integer, ByVal capacidad As Byte, ByVal vig As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarMesa", ReplyAction:="*")>  _
        Function guardarMesaAsync(ByVal id As Integer, ByVal numero As Integer, ByVal capacidad As Byte, ByVal vig As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub modificarMesa(ByVal id As Integer, ByVal numero As Integer, ByVal capacidad As Byte, ByVal vig As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarMesa", ReplyAction:="*")>  _
        Function modificarMesaAsync(ByVal id As Integer, ByVal numero As Integer, ByVal capacidad As Byte, ByVal vig As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub eliminarMesa(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarMesa", ReplyAction:="*")>  _
        Function eliminarMesaAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darBajaMesa(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaMesa", ReplyAction:="*")>  _
        Function darBajaMesaAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darAltaMesa(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaMesa", ReplyAction:="*")>  _
        Function darAltaMesaAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarMesas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarMesas() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarMesas", ReplyAction:="*")>  _
        Function listarMesasAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarMesa(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarMesa", ReplyAction:="*")>  _
        Function buscarMesaAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificarMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerificarMesa(ByVal idMesa As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificarMesa", ReplyAction:="*")>  _
        Function VerificarMesaAsync(ByVal idMesa As Integer) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsMesaSoapChannel
        Inherits srMesa.wsMesaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsMesaSoapClient
        Inherits System.ServiceModel.ClientBase(Of srMesa.wsMesaSoap)
        Implements srMesa.wsMesaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function generarIDMesa() As Integer Implements srMesa.wsMesaSoap.generarIDMesa
            Return MyBase.Channel.generarIDMesa
        End Function
        
        Public Function generarIDMesaAsync() As System.Threading.Tasks.Task(Of Integer) Implements srMesa.wsMesaSoap.generarIDMesaAsync
            Return MyBase.Channel.generarIDMesaAsync
        End Function
        
        Public Sub guardarMesa(ByVal id As Integer, ByVal numero As Integer, ByVal capacidad As Byte, ByVal vig As Boolean) Implements srMesa.wsMesaSoap.guardarMesa
            MyBase.Channel.guardarMesa(id, numero, capacidad, vig)
        End Sub
        
        Public Function guardarMesaAsync(ByVal id As Integer, ByVal numero As Integer, ByVal capacidad As Byte, ByVal vig As Boolean) As System.Threading.Tasks.Task Implements srMesa.wsMesaSoap.guardarMesaAsync
            Return MyBase.Channel.guardarMesaAsync(id, numero, capacidad, vig)
        End Function
        
        Public Sub modificarMesa(ByVal id As Integer, ByVal numero As Integer, ByVal capacidad As Byte, ByVal vig As Boolean) Implements srMesa.wsMesaSoap.modificarMesa
            MyBase.Channel.modificarMesa(id, numero, capacidad, vig)
        End Sub
        
        Public Function modificarMesaAsync(ByVal id As Integer, ByVal numero As Integer, ByVal capacidad As Byte, ByVal vig As Boolean) As System.Threading.Tasks.Task Implements srMesa.wsMesaSoap.modificarMesaAsync
            Return MyBase.Channel.modificarMesaAsync(id, numero, capacidad, vig)
        End Function
        
        Public Sub eliminarMesa(ByVal id As Integer) Implements srMesa.wsMesaSoap.eliminarMesa
            MyBase.Channel.eliminarMesa(id)
        End Sub
        
        Public Function eliminarMesaAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srMesa.wsMesaSoap.eliminarMesaAsync
            Return MyBase.Channel.eliminarMesaAsync(id)
        End Function
        
        Public Sub darBajaMesa(ByVal id As Integer) Implements srMesa.wsMesaSoap.darBajaMesa
            MyBase.Channel.darBajaMesa(id)
        End Sub
        
        Public Function darBajaMesaAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srMesa.wsMesaSoap.darBajaMesaAsync
            Return MyBase.Channel.darBajaMesaAsync(id)
        End Function
        
        Public Sub darAltaMesa(ByVal id As Integer) Implements srMesa.wsMesaSoap.darAltaMesa
            MyBase.Channel.darAltaMesa(id)
        End Sub
        
        Public Function darAltaMesaAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srMesa.wsMesaSoap.darAltaMesaAsync
            Return MyBase.Channel.darAltaMesaAsync(id)
        End Function
        
        Public Function listarMesas() As System.Data.DataTable Implements srMesa.wsMesaSoap.listarMesas
            Return MyBase.Channel.listarMesas
        End Function
        
        Public Function listarMesasAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srMesa.wsMesaSoap.listarMesasAsync
            Return MyBase.Channel.listarMesasAsync
        End Function
        
        Public Function buscarMesa(ByVal id As Integer) As System.Data.DataTable Implements srMesa.wsMesaSoap.buscarMesa
            Return MyBase.Channel.buscarMesa(id)
        End Function
        
        Public Function buscarMesaAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srMesa.wsMesaSoap.buscarMesaAsync
            Return MyBase.Channel.buscarMesaAsync(id)
        End Function
        
        Public Function VerificarMesa(ByVal idMesa As Integer) As Boolean Implements srMesa.wsMesaSoap.VerificarMesa
            Return MyBase.Channel.VerificarMesa(idMesa)
        End Function
        
        Public Function VerificarMesaAsync(ByVal idMesa As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements srMesa.wsMesaSoap.VerificarMesaAsync
            Return MyBase.Channel.VerificarMesaAsync(idMesa)
        End Function
    End Class
End Namespace
