'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srPedido
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srPedido.wsPedidoSoap")>  _
    Public Interface wsPedidoSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarPedidoActivoPorMesa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BuscarPedidoActivoPorMesa(ByVal idMesa As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarPedidoActivoPorMesa", ReplyAction:="*")>  _
        Function BuscarPedidoActivoPorMesaAsync(ByVal idMesa As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarDetallesPorId", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarDetallesPorId(ByVal idPedido As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarDetallesPorId", ReplyAction:="*")>  _
        Function ListarDetallesPorIdAsync(ByVal idPedido As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarHistorialDePedidos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarHistorialDePedidos() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarHistorialDePedidos", ReplyAction:="*")>  _
        Function ListarHistorialDePedidosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RegistrarPedido", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub RegistrarPedido(ByVal idCliente As Integer, ByVal idMesero As Integer, ByVal idMesa As Integer, ByVal detalles() As srPedido.DetallePedidoItem)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RegistrarPedido", ReplyAction:="*")>  _
        Function RegistrarPedidoAsync(ByVal idCliente As Integer, ByVal idMesero As Integer, ByVal idMesa As Integer, ByVal detalles() As srPedido.DetallePedidoItem) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActualizarPedido", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub ActualizarPedido(ByVal idPedido As Integer, ByVal nuevosDetalles() As srPedido.DetallePedidoItem)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActualizarPedido", ReplyAction:="*")>  _
        Function ActualizarPedidoAsync(ByVal idPedido As Integer, ByVal nuevosDetalles() As srPedido.DetallePedidoItem) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ProcesarPago", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub ProcesarPago(ByVal idPedido As Integer, ByVal idCajero As Integer, ByVal idCliente As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ProcesarPago", ReplyAction:="*")>  _
        Function ProcesarPagoAsync(ByVal idPedido As Integer, ByVal idCajero As Integer, ByVal idCliente As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ContarPedidosHoy", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ContarPedidosHoy() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ContarPedidosHoy", ReplyAction:="*")>  _
        Function ContarPedidosHoyAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ContarPedidosPendientes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ContarPedidosPendientes() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ContarPedidosPendientes", ReplyAction:="*")>  _
        Function ContarPedidosPendientesAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ProductoMasVendido", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ProductoMasVendido() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ProductoMasVendido", ReplyAction:="*")>  _
        Function ProductoMasVendidoAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VentasUltimos7Dias", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VentasUltimos7Dias() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VentasUltimos7Dias", ReplyAction:="*")>  _
        Function VentasUltimos7DiasAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ContarPedidosPorEstado", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ContarPedidosPorEstado(ByVal estadoPago As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ContarPedidosPorEstado", ReplyAction:="*")>  _
        Function ContarPedidosPorEstadoAsync(ByVal estadoPago As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReporteDesempenoMeseros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetReporteDesempenoMeseros() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReporteDesempenoMeseros", ReplyAction:="*")>  _
        Function GetReporteDesempenoMeserosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReporteProductosVendidos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetReporteProductosVendidos() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReporteProductosVendidos", ReplyAction:="*")>  _
        Function GetReporteProductosVendidosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReporteVentasPorCategoria", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetReporteVentasPorCategoria() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReporteVentasPorCategoria", ReplyAction:="*")>  _
        Function GetReporteVentasPorCategoriaAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DetallePedidoItem
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idProductoField As Integer
        
        Private nombreField As String
        
        Private precioField As Decimal
        
        Private cantidadField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IdProducto() As Integer
            Get
                Return Me.idProductoField
            End Get
            Set
                Me.idProductoField = value
                Me.RaisePropertyChanged("IdProducto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("Nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Precio() As Decimal
            Get
                Return Me.precioField
            End Get
            Set
                Me.precioField = value
                Me.RaisePropertyChanged("Precio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Cantidad() As Integer
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
                Me.RaisePropertyChanged("Cantidad")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsPedidoSoapChannel
        Inherits srPedido.wsPedidoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsPedidoSoapClient
        Inherits System.ServiceModel.ClientBase(Of srPedido.wsPedidoSoap)
        Implements srPedido.wsPedidoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function BuscarPedidoActivoPorMesa(ByVal idMesa As Integer) As System.Data.DataTable Implements srPedido.wsPedidoSoap.BuscarPedidoActivoPorMesa
            Return MyBase.Channel.BuscarPedidoActivoPorMesa(idMesa)
        End Function
        
        Public Function BuscarPedidoActivoPorMesaAsync(ByVal idMesa As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srPedido.wsPedidoSoap.BuscarPedidoActivoPorMesaAsync
            Return MyBase.Channel.BuscarPedidoActivoPorMesaAsync(idMesa)
        End Function
        
        Public Function ListarDetallesPorId(ByVal idPedido As Integer) As System.Data.DataTable Implements srPedido.wsPedidoSoap.ListarDetallesPorId
            Return MyBase.Channel.ListarDetallesPorId(idPedido)
        End Function
        
        Public Function ListarDetallesPorIdAsync(ByVal idPedido As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srPedido.wsPedidoSoap.ListarDetallesPorIdAsync
            Return MyBase.Channel.ListarDetallesPorIdAsync(idPedido)
        End Function
        
        Public Function ListarHistorialDePedidos() As System.Data.DataTable Implements srPedido.wsPedidoSoap.ListarHistorialDePedidos
            Return MyBase.Channel.ListarHistorialDePedidos
        End Function
        
        Public Function ListarHistorialDePedidosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srPedido.wsPedidoSoap.ListarHistorialDePedidosAsync
            Return MyBase.Channel.ListarHistorialDePedidosAsync
        End Function
        
        Public Sub RegistrarPedido(ByVal idCliente As Integer, ByVal idMesero As Integer, ByVal idMesa As Integer, ByVal detalles() As srPedido.DetallePedidoItem) Implements srPedido.wsPedidoSoap.RegistrarPedido
            MyBase.Channel.RegistrarPedido(idCliente, idMesero, idMesa, detalles)
        End Sub
        
        Public Function RegistrarPedidoAsync(ByVal idCliente As Integer, ByVal idMesero As Integer, ByVal idMesa As Integer, ByVal detalles() As srPedido.DetallePedidoItem) As System.Threading.Tasks.Task Implements srPedido.wsPedidoSoap.RegistrarPedidoAsync
            Return MyBase.Channel.RegistrarPedidoAsync(idCliente, idMesero, idMesa, detalles)
        End Function
        
        Public Sub ActualizarPedido(ByVal idPedido As Integer, ByVal nuevosDetalles() As srPedido.DetallePedidoItem) Implements srPedido.wsPedidoSoap.ActualizarPedido
            MyBase.Channel.ActualizarPedido(idPedido, nuevosDetalles)
        End Sub
        
        Public Function ActualizarPedidoAsync(ByVal idPedido As Integer, ByVal nuevosDetalles() As srPedido.DetallePedidoItem) As System.Threading.Tasks.Task Implements srPedido.wsPedidoSoap.ActualizarPedidoAsync
            Return MyBase.Channel.ActualizarPedidoAsync(idPedido, nuevosDetalles)
        End Function
        
        Public Sub ProcesarPago(ByVal idPedido As Integer, ByVal idCajero As Integer, ByVal idCliente As Integer) Implements srPedido.wsPedidoSoap.ProcesarPago
            MyBase.Channel.ProcesarPago(idPedido, idCajero, idCliente)
        End Sub
        
        Public Function ProcesarPagoAsync(ByVal idPedido As Integer, ByVal idCajero As Integer, ByVal idCliente As Integer) As System.Threading.Tasks.Task Implements srPedido.wsPedidoSoap.ProcesarPagoAsync
            Return MyBase.Channel.ProcesarPagoAsync(idPedido, idCajero, idCliente)
        End Function
        
        Public Function ContarPedidosHoy() As Integer Implements srPedido.wsPedidoSoap.ContarPedidosHoy
            Return MyBase.Channel.ContarPedidosHoy
        End Function
        
        Public Function ContarPedidosHoyAsync() As System.Threading.Tasks.Task(Of Integer) Implements srPedido.wsPedidoSoap.ContarPedidosHoyAsync
            Return MyBase.Channel.ContarPedidosHoyAsync
        End Function
        
        Public Function ContarPedidosPendientes() As Integer Implements srPedido.wsPedidoSoap.ContarPedidosPendientes
            Return MyBase.Channel.ContarPedidosPendientes
        End Function
        
        Public Function ContarPedidosPendientesAsync() As System.Threading.Tasks.Task(Of Integer) Implements srPedido.wsPedidoSoap.ContarPedidosPendientesAsync
            Return MyBase.Channel.ContarPedidosPendientesAsync
        End Function
        
        Public Function ProductoMasVendido() As String Implements srPedido.wsPedidoSoap.ProductoMasVendido
            Return MyBase.Channel.ProductoMasVendido
        End Function
        
        Public Function ProductoMasVendidoAsync() As System.Threading.Tasks.Task(Of String) Implements srPedido.wsPedidoSoap.ProductoMasVendidoAsync
            Return MyBase.Channel.ProductoMasVendidoAsync
        End Function
        
        Public Function VentasUltimos7Dias() As System.Data.DataTable Implements srPedido.wsPedidoSoap.VentasUltimos7Dias
            Return MyBase.Channel.VentasUltimos7Dias
        End Function
        
        Public Function VentasUltimos7DiasAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srPedido.wsPedidoSoap.VentasUltimos7DiasAsync
            Return MyBase.Channel.VentasUltimos7DiasAsync
        End Function
        
        Public Function ContarPedidosPorEstado(ByVal estadoPago As Integer) As Integer Implements srPedido.wsPedidoSoap.ContarPedidosPorEstado
            Return MyBase.Channel.ContarPedidosPorEstado(estadoPago)
        End Function
        
        Public Function ContarPedidosPorEstadoAsync(ByVal estadoPago As Integer) As System.Threading.Tasks.Task(Of Integer) Implements srPedido.wsPedidoSoap.ContarPedidosPorEstadoAsync
            Return MyBase.Channel.ContarPedidosPorEstadoAsync(estadoPago)
        End Function
        
        Public Function GetReporteDesempenoMeseros() As System.Data.DataTable Implements srPedido.wsPedidoSoap.GetReporteDesempenoMeseros
            Return MyBase.Channel.GetReporteDesempenoMeseros
        End Function
        
        Public Function GetReporteDesempenoMeserosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srPedido.wsPedidoSoap.GetReporteDesempenoMeserosAsync
            Return MyBase.Channel.GetReporteDesempenoMeserosAsync
        End Function
        
        Public Function GetReporteProductosVendidos() As System.Data.DataTable Implements srPedido.wsPedidoSoap.GetReporteProductosVendidos
            Return MyBase.Channel.GetReporteProductosVendidos
        End Function
        
        Public Function GetReporteProductosVendidosAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srPedido.wsPedidoSoap.GetReporteProductosVendidosAsync
            Return MyBase.Channel.GetReporteProductosVendidosAsync
        End Function
        
        Public Function GetReporteVentasPorCategoria() As System.Data.DataTable Implements srPedido.wsPedidoSoap.GetReporteVentasPorCategoria
            Return MyBase.Channel.GetReporteVentasPorCategoria
        End Function
        
        Public Function GetReporteVentasPorCategoriaAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srPedido.wsPedidoSoap.GetReporteVentasPorCategoriaAsync
            Return MyBase.Channel.GetReporteVentasPorCategoriaAsync
        End Function
    End Class
End Namespace
