'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srTipoProducto
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srTipoProducto.wsTipoProductoSoap")>  _
    Public Interface wsTipoProductoSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDTipoProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function generarIDTipoProducto() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/generarIDTipoProducto", ReplyAction:="*")>  _
        Function generarIDTipoProductoAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarTipoProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub guardarTipoProducto(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardarTipoProducto", ReplyAction:="*")>  _
        Function guardarTipoProductoAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarTipoProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub modificarTipoProducto(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/modificarTipoProducto", ReplyAction:="*")>  _
        Function modificarTipoProductoAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarTipoProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub eliminarTipoProducto(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminarTipoProducto", ReplyAction:="*")>  _
        Function eliminarTipoProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaTipoProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darBajaTipoProducto(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darBajaTipoProducto", ReplyAction:="*")>  _
        Function darBajaTipoProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaTipoProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub darAltaTipoProducto(ByVal id As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/darAltaTipoProducto", ReplyAction:="*")>  _
        Function darAltaTipoProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarTipoProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buscarTipoProducto(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/buscarTipoProducto", ReplyAction:="*")>  _
        Function buscarTipoProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarTiposProducto", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listarTiposProducto() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/listarTiposProducto", ReplyAction:="*")>  _
        Function listarTiposProductoAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsTipoProductoSoapChannel
        Inherits srTipoProducto.wsTipoProductoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsTipoProductoSoapClient
        Inherits System.ServiceModel.ClientBase(Of srTipoProducto.wsTipoProductoSoap)
        Implements srTipoProducto.wsTipoProductoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function generarIDTipoProducto() As Integer Implements srTipoProducto.wsTipoProductoSoap.generarIDTipoProducto
            Return MyBase.Channel.generarIDTipoProducto
        End Function
        
        Public Function generarIDTipoProductoAsync() As System.Threading.Tasks.Task(Of Integer) Implements srTipoProducto.wsTipoProductoSoap.generarIDTipoProductoAsync
            Return MyBase.Channel.generarIDTipoProductoAsync
        End Function
        
        Public Sub guardarTipoProducto(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) Implements srTipoProducto.wsTipoProductoSoap.guardarTipoProducto
            MyBase.Channel.guardarTipoProducto(id, nom, desc, vig)
        End Sub
        
        Public Function guardarTipoProductoAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task Implements srTipoProducto.wsTipoProductoSoap.guardarTipoProductoAsync
            Return MyBase.Channel.guardarTipoProductoAsync(id, nom, desc, vig)
        End Function
        
        Public Sub modificarTipoProducto(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) Implements srTipoProducto.wsTipoProductoSoap.modificarTipoProducto
            MyBase.Channel.modificarTipoProducto(id, nom, desc, vig)
        End Sub
        
        Public Function modificarTipoProductoAsync(ByVal id As Integer, ByVal nom As String, ByVal desc As String, ByVal vig As Boolean) As System.Threading.Tasks.Task Implements srTipoProducto.wsTipoProductoSoap.modificarTipoProductoAsync
            Return MyBase.Channel.modificarTipoProductoAsync(id, nom, desc, vig)
        End Function
        
        Public Sub eliminarTipoProducto(ByVal id As Integer) Implements srTipoProducto.wsTipoProductoSoap.eliminarTipoProducto
            MyBase.Channel.eliminarTipoProducto(id)
        End Sub
        
        Public Function eliminarTipoProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srTipoProducto.wsTipoProductoSoap.eliminarTipoProductoAsync
            Return MyBase.Channel.eliminarTipoProductoAsync(id)
        End Function
        
        Public Sub darBajaTipoProducto(ByVal id As Integer) Implements srTipoProducto.wsTipoProductoSoap.darBajaTipoProducto
            MyBase.Channel.darBajaTipoProducto(id)
        End Sub
        
        Public Function darBajaTipoProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srTipoProducto.wsTipoProductoSoap.darBajaTipoProductoAsync
            Return MyBase.Channel.darBajaTipoProductoAsync(id)
        End Function
        
        Public Sub darAltaTipoProducto(ByVal id As Integer) Implements srTipoProducto.wsTipoProductoSoap.darAltaTipoProducto
            MyBase.Channel.darAltaTipoProducto(id)
        End Sub
        
        Public Function darAltaTipoProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task Implements srTipoProducto.wsTipoProductoSoap.darAltaTipoProductoAsync
            Return MyBase.Channel.darAltaTipoProductoAsync(id)
        End Function
        
        Public Function buscarTipoProducto(ByVal id As Integer) As System.Data.DataTable Implements srTipoProducto.wsTipoProductoSoap.buscarTipoProducto
            Return MyBase.Channel.buscarTipoProducto(id)
        End Function
        
        Public Function buscarTipoProductoAsync(ByVal id As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srTipoProducto.wsTipoProductoSoap.buscarTipoProductoAsync
            Return MyBase.Channel.buscarTipoProductoAsync(id)
        End Function
        
        Public Function listarTiposProducto() As System.Data.DataTable Implements srTipoProducto.wsTipoProductoSoap.listarTiposProducto
            Return MyBase.Channel.listarTiposProducto
        End Function
        
        Public Function listarTiposProductoAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements srTipoProducto.wsTipoProductoSoap.listarTiposProductoAsync
            Return MyBase.Channel.listarTiposProductoAsync
        End Function
    End Class
End Namespace
